### PR TITLE
Make window dataset use annotation.from df #110

### PR DESCRIPTION
**Pull request by NickleDave**

### CODE REVIEW

**Comment by NickleDave** [comment]
@yardencsGitHub I tested whether this fix breaks anything for .cbin + .not.mat files; `vak train` is still working for me after adding it

Can you do as before and check out the branch to test if it fixes your bug, before I merge it in?

Please if you get an error, comment here with the complete traceback to help me debug.

**Comment by yardencsGitHub** [comment]
I checked out the new branch
(git checkout make-WindowDataset-use-annotation.from_df-#110)

and ran vak train.

Got the following error message:

vak train config-llb3-04232019.toml
Logging results to D:\YardenBirds\llb3_spring\results\results_200330_144813
Size of each timebin in spectrogram, in seconds: 0.003
using training dataset from D:\YardenBirds\llb3_spring\train\annotated_prep_200326_103845.csv
Traceback (most recent call last):
  File "C:\Anaconda3\envs\tweetyenv_alpha\Scripts\vak-script.py", line 11, in <module>
    load_entry_point('vak', 'console_scripts', 'vak')()
  File "c:\users\yarden cohen\repos\vak\src\vak\__main__.py", line 43, in main
    config_file=args.configfile)
  File "c:\users\yarden cohen\repos\vak\src\vak\cli\cli.py", line 21, in cli
    train(toml_path=config_file)
  File "c:\users\yarden cohen\repos\vak\src\vak\cli\train.py", line 119, in train
    target_transform=target_transform
  File "c:\users\yarden cohen\repos\vak\src\vak\datasets\window_dataset.py", line 221, in from_csv
    annots = util.annotation.from_df(df)
  File "c:\users\yarden cohen\repos\vak\src\vak\util\annotation.py", line 82, in from_df
    'unable to load labels from dataframe; found a single annotation file associated with all '
ValueError: unable to load labels from dataframe; found a single annotation file associated with all rows in dataframe, but loading it did not return a list of annotations for each row.
Single annotation file: D:\YardenBirds\llb3_spring\llb3_annotation_Apr_2019_emily_4TF.matLoading it returned a <class 'list'>.

It fails because the test
len(annots) == len(vak_df) fails 
annots has 2655 entries (same as number of spectrogram files) and len(vak_df) is 777
(I don't know what is that number)

**Comment by NickleDave** [comment]
We need to figure out why there are less rows in `vak_df`.
Is it because `vak prep` did not add all the spectrogram files?
Maybe because you specified a `labelset` and some of the files have annotations with labels that are not in the `labelset`?

If you re-run `vak prep` without a `labelset` specified, does it include all 2655 spectrogram files, and does `vak train` now work when you do that?

Easiest way to check the length of the csv file in Python might be 
```
import pandas as pd
df = pd.read_csv('file_made_by_prep.csv')
len(df)
```

**Comment by yardencsGitHub** [comment]
Loading the csv file with pandas resulted in the correct number (2655)

Commenting out the labelset line in [PREP] resulted in a crash.

**Comment by NickleDave** [comment]
I see, thank you.

Can you attach both the .csv file and the current version of the config file? (without the labelset commented out)

Can you please also reply with the traceback from the error when labelset was commented out? Not clear to me if that's a separate error

**Comment by yardencsGitHub** [comment]
[toml_and_csv.zip](https://github.com/NickleDave/vak/files/4411762/toml_and_csv.zip)

When the labelset is commented out running vak prep:

vak prep config-llb3-04232019.toml
[########################################] | 100% Completed | 28.4s
c:\users\yarden cohen\repos\vak\src\vak\util\split.py:64: UserWarning: Total target duration of training, test, and (if specified) validation sets, 13000.0 seconds, is less than total duration of dataset: 33734.391. Not all of dataset will be used.
  'Total target duration of training, test, and (if specified) validation sets, '
Traceback (most recent call last):
  File "C:\Anaconda3\envs\tweetyenv_alpha\Scripts\vak-script.py", line 11, in <module>
    load_entry_point('vak', 'console_scripts', 'vak')()
  File "c:\users\yarden cohen\repos\vak\src\vak\__main__.py", line 43, in main
    config_file=args.configfile)
  File "c:\users\yarden cohen\repos\vak\src\vak\cli\cli.py", line 18, in cli
    prep(toml_path=config_file)
  File "c:\users\yarden cohen\repos\vak\src\vak\cli\prep.py", line 165, in prep
    test_dur=cfg.prep.test_dur)
  File "c:\users\yarden cohen\repos\vak\src\vak\util\split.py", line 135, in train_test_dur_split
    val_dur=val_dur)
  File "c:\users\yarden cohen\repos\vak\src\vak\util\split.py", line 81, in train_test_dur_split_inds
    test_dur)
  File "c:\users\yarden cohen\repos\vak\src\vak\util\splitalgos\bruteforce.py", line 208, in brute_force
    if train_labels != set(labelset):
TypeError: 'NoneType' object is not iterable

**Comment by NickleDave** [comment]
Thank you, that helps.

I downloaded llb3 from Drive to help debug, will see if I can reproduce the error on my machine.

**Comment by yardencsGitHub** [comment]
Thanks

I’m working in the ‘make-windows-dataset..’ branch.

Also, you bumped Tweety’s version to 0.3.1.
Is this a code change? Or a formal thing?  

On Mar 31, 2020, at 10:08 PM, David Nicholson <notifications@github.com> wrote:


Thank you, that helps.

I downloaded llb3 from Drive to help debug, will see if I can reproduce the error on my machine.

**Comment by NickleDave** [comment]
oh whoops, I forgot to push the update to the CHANGELOG. It's there now:
https://github.com/yardencsGitHub/tweetynet/commit/3ba77572770c094aa94ff067936e1d8c91a0878e

I want the converter functions to return labels as strings.
Another way to do this would be to silently cast them to strings internally but I want it to be obvious that it's happening. Maybe later we can think about ways to enforce types on the DataFrame but for now this is a quick solution, so we don't have the added complexity of dealing with multiple label types (e.g. str and int) that can cause different types of errors (e.g. `prep` not adding a file because it doesn't contain any labels in `labelset`, but only because the annotation uses `int {1,2,3,4,5}` but `labelset` is `str{'1', '2', '3', '4', '5'}`)

**Comment by NickleDave** [comment]
I have the `llb3` dataset and am testing locally.
One of the files was corrupted after download and that's causing a different error--I moved it out of the folder and then `vak` complains because it can't match every annotation with a spect file.

This is annoying though, I think we want it to only complain if it can't match all the spect files with annotations, but not the other way around. I.e., it should only try to match every file in `data_dir` with an annotation, even if you give it a file full of a million annotations--it shouldn't try to match all those annotations with files and crash if it can't.
I raised an issue on this (#124) and I think I see a relatively clean way to fix it.

**Comment by NickleDave** [comment]
@yardencsGitHub I made a bunch of fixes and rebased this branch on master after doing so.

I can get `prep` to run but it always crashes because it can't split the dataset:
```
Traceback (most recent call last):
  File "/Users/davidnicholson/opt/anaconda3/envs/vak-dev/bin/vak", line 11, in <module>
    load_entry_point('vak', 'console_scripts', 'vak')()
  File "/Users/davidnicholson/Documents/repos/coding/vocal/vak/src/vak/__main__.py", line 43, in main
    config_file=args.configfile)
  File "/Users/davidnicholson/Documents/repos/coding/vocal/vak/src/vak/cli/cli.py", line 18, in cli
    prep(toml_path=config_file)
  File "/Users/davidnicholson/Documents/repos/coding/vocal/vak/src/vak/cli/prep.py", line 165, in prep
    test_dur=cfg.prep.test_dur)
  File "/Users/davidnicholson/Documents/repos/coding/vocal/vak/src/vak/util/split.py", line 126, in train_test_dur_split
    durs = vak_df['duration'].values
  File "/Users/davidnicholson/Documents/repos/coding/vocal/vak/src/vak/util/split.py", line 81, in train_test_dur_split_inds
    test_dur)
  File "/Users/davidnicholson/Documents/repos/coding/vocal/vak/src/vak/util/splitalgos/bruteforce.py", line 234, in brute_force
    raise ValueError(all_labels_err)
ValueError: Did not successfully divide data into training, validation, and test sets of sufficient duration after 5000 iterations. Try increasing the total size of the data set.
```

I used `pdb` to verify that label types match, i.e. that labels loaded from the annotations and the labels in labelset are both strings. They are.

Not sure if it's the number of files I'm using?
I have copied  all files from 4/26, 4/28, and 5/3 into one directory which gives me 861 files.
Then I run the attached .toml config and get the error.
Can you verify whether you run into the same issue?
You'll want to either execute `git pull --rebase` in this branch or just clone the repo again and check it out in there. And you'll need `tweetynet 0.3.1`
[config-llb3-04232019.toml 2.zip](https://github.com/NickleDave/vak/files/4424726/config-llb3-04232019.toml.2.zip)

**Comment by yardencsGitHub** [comment]
First, this .toml file doesn't define the 'test_dur' .. is it defined elsewhere?
I confirm that all 20 syllable types exist in the 860 files (I double checked.. not 861)  in those dates and in descent number of files. 

I rebased in that branched and used tweety = 0.3.1.

First, I tested the case where the annotation file doesn't cover all existing files (I created a new annotation file that only covers the 860 files above). This didn't work because vak prep seeks annotations for all files in the folder.

Next, I created a new folder with just the 860 files and ran vak prep with the annotation covering all 2655 files. I changed the dataset durations to test,val,train = 1000.. it worked

**Comment by yardencsGitHub** [comment]
I tried vak train and it works!
At least .. it did not crash thus far.
Is this because the labels are all converted to strings now?
How did this solve the call "annot.seq.labels" that used to cause errors?

**Comment by NickleDave** [comment]
@yardencsGitHub do you have `device = "cuda"` in the [TRAIN] section of your config?
What happens if you runs `nvidia-smi` during training, how much of the GPU memory is being used? You could try increasing the number of workers, e.g. `num_workers = 8` and see if that helps. We can also try implementing `dataparallel`

**Comment by NickleDave** [comment]
In response to your first comment above:

> First, this .toml file doesn't define the 'test_dur' .. is it defined elsewhere?
You don't have to define a `test_dur`.
Users training a model are not necessarily going to want to perform a rigorous test of metrics.


> First, I tested the case where the annotation file doesn't cover all existing files (I created a new annotation file that only covers the 860 files above). This didn't work because vak prep seeks annotations for all files in the folder.
Thank you for testing this case, good to know

> Next, I created a new folder with just the 860 files and ran vak prep with the annotation covering all 2655 files. I changed the dataset durations to test,val,train = 1000.. it worked
> 
> I tried vak train and it works!
Great!

> At least .. it did not crash thus far.
> Is this because the labels are all converted to strings now?
> How did this solve the call "annot.seq.labels" that used to cause errors?
There were multiple issues, the main solution was calling the same function that I wrote to fix the same errors you identified with `prep` in the `__getitem__` method of `WindowDataset`.

I will go ahead and merge this PR and close the related issues

**Pull request merged**
