### PR TITLE
fix bruteforce.py to ensure all tags exist in sets

### PR DESCRIPTION
**Pull request by yardencsGitHub**
In this version ../split/algorithms/bruteforce.py I start by first making sure each label is represented in the required sets (train,test,validate).

Briefly,
The added code loops through all labels and adds files containing these labels to each set iff the set does not already contain the labels.

Then files are added randomly to meet the required duration of the sets

### CODE REVIEW

**Comment by yardencsGitHub** [comment]
@NickleDave , I read through your last commit and some property may be missing 
(at least, I did not find it)
In my script I kept an array to track which labels and files were already used.
**label_containing_inds[ind,:] = 0** remove files from that array.
This makes sure that when searching for files containing the next label it will not be possible to pull the file already popped for the current label.

Unless I missed it, this logic does not exist in your commit. Right?

**Comment by NickleDave** [comment]
@yardencsGitHub can you attach a .toml config file for llb16 to this PR please so I can use it to test

**Comment by NickleDave** [comment]
I figured out the right `rangestr` but if you can tell me what duration splits you are using that would help with testing

**Comment by NickleDave** [comment]
I tested using 20k s for the train set.

When trying for a subset of size 180, all 3 versions are successful 100 / 100 times.

When trying for a subset of 60, though, the old version is successful 4/20 times, the other 2 work 20/20!

Going to try again overnight with 100 runs (takes a bit the way I'm running it now) ... but if the results is basically the same I'll probably just clean up the commits and merge this in.

Either way it's helped me see how I can further clean up this function anyway to reduce repitition -- will probably do that right after.

**Comment by NickleDave** [comment]
@yardencsGitHub as I noted in the updated commit

```
Testing on one canary with 30 labels (!), found
that this modified version of the function
worked 100% of the time while the old version
only worked 20% of the time
```

I'll take that as an improvement.
Thanks!

Merging this one in.

**Pull request merged**
